CREATE SCHEMA `SalesManager_db`;
USE `SalesManager_db`;

CREATE TABLE	`KHACH_HANG` (
MA_KH bigint NOT NULL AUTO_INCREMENT, 
HO_TEN nvarchar(50), 
DIA_CHI Nvarchar(100), 
SO_DIEN_THOAI  Varchar(11),
EMAIL Varchar(50),
PRIMARY KEY (MA_KH)
);

CREATE TABLE 	`NHAN_VIEN`  ( 
MA_NV bigint NOT NULL AUTO_INCREMENT,
HO_TEN nvarchar(50), 
DIA_CHI Nvarchar(100), 
SO_DIEN_THOAI  Varchar(11),
EMAIL Varchar(50),
GIOI_TINH bit,
PRIMARY KEY (MA_NV)
);

CREATE TABLE `PHIEU_DAT_HANG` (
MA_PHIEU_DH bigint NOT NULL AUTO_INCREMENT,
MA_NV bigint,
MA_KH bigint, 
NGAY_GIO_DAT datetime, 
NGAY_GIO_GIAO datetime, 
TONG_TIEN double, 
TRANG_THAI bit,
PRIMARY KEY (MA_PHIEU_DH)
);

CREATE TABLE	`CHI_TIET_THANH_TOAN` (
MA_KH bigint,
MA_PHIEU_DH bigint ,
THO_DIEM_TT datetime
);

CREATE TABLE	`NUOC_UONG`(
MA_NUOC bigint NOT NULL AUTO_INCREMENT,
MA_DM_NUOC bigint,
TEN_NUOC_UONG nvarchar(50),  
DON_GIA double, 
DON_VI_TINH nvarchar (20),
SO_LUONG_TON bigint,
PRIMARY KEY (MA_NUOC)
);

CREATE TABLE	`DANH_MUC_NUOC_UONG`(
MA_DM_NUOC bigint NOT NULL AUTO_INCREMENT,
TEN_DM nvarchar(30),
 PRIMARY KEY (MA_DM_NUOC)
);

CREATE TABLE	`CHI_TIET_GOI_NUOC`(
MA_PHIEU_DH bigint, 
MA_NUOC bigint, 
DON_GIA double,
SO_LUONG bigint, 
THANH_TIEN double
);

CREATE TABLE	`DO_AN_KEM`(
MA_DOAN bigint NOT NULL AUTO_INCREMENT,
MA_DM_DOAN bigint,
TEN_DO_AN nvarchar(50),  
DON_GIA double, 
DON_VI_TINH nvarchar (20),
SO_LUONG_TON bigint,
PRIMARY KEY (MA_DOAN)
);

CREATE TABLE	`DANH_MUC_DO_AN`(
MA_DM_DOAN bigint NOT NULL AUTO_INCREMENT,
TEN_DM nvarchar(30),
 PRIMARY KEY (MA_DM_DOAN)
);

CREATE TABLE	`CHI_TIET_DO_AN`(
MA_PHIEU_DH bigint, 
MA_DOAN bigint, 
DON_GIA double,
SO_LUONG bigint, 
THANH_TIEN double

);

ALTER TABLE PHIEU_DAT_HANG
ADD FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH);
ALTER TABLE PHIEU_DAT_HANG
ADD FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN(MA_NV);
ALTER TABLE CHI_TIET_THANH_TOAN
ADD FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH);
ALTER TABLE CHI_TIET_THANH_TOAN
ADD FOREIGN KEY (MA_PHIEU_DH) REFERENCES PHIEU_DAT_HANG(MA_PHIEU_DH);
ALTER TABLE NUOC_UONG
ADD FOREIGN KEY (MA_DM_NUOC) REFERENCES DANH_MUC_NUOC_UONG(MA_DM_NUOC);
ALTER TABLE CHI_TIET_GOI_NUOC
ADD FOREIGN KEY (MA_PHIEU_DH) REFERENCES PHIEU_DAT_HANG(MA_PHIEU_DH);
ALTER TABLE CHI_TIET_GOI_NUOC
ADD FOREIGN KEY (MA_NUOC) REFERENCES NUOC_UONG(MA_NUOC);
ALTER TABLE DO_AN_KEM
ADD FOREIGN KEY (MA_DM_DOAN) REFERENCES DANH_MUC_DO_AN(MA_DM_DOAN);
ALTER TABLE CHI_TIET_DO_AN
ADD FOREIGN KEY (MA_PHIEU_DH) REFERENCES PHIEU_DAT_HANG(MA_PHIEU_DH);
ALTER TABLE CHI_TIET_DO_AN
ADD FOREIGN KEY (MA_DOAN) REFERENCES DO_AN_KEM(MA_DOAN);